import './globals.css'
// import { commonpixel } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.cdnfonts.com/css/minecraft-4" rel="stylesheet" />

      </head>
      <body>{children}</body>
    </html>
  )
}
